# Generated by Django 4.2.8 on 2023-12-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swimming_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="swimmer",
            table="swimmer",
        ),
    ]
