-- Dirty Read Transaction 2

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
-- Solution for the dirty read:
-- SET TRANSACTION ISOLATION LEVEL READ COMMITTED

BEGIN TRANSACTION
SELECT * FROM Team
WAITFOR DELAY '00:00:15'
SELECT * FROM Team
COMMIT TRAN