-- Non-repeatable read Transaction 2

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
-- Solution for the non-repeatable read:
-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

BEGIN TRANSACTION
SELECT * FROM Team;
WAITFOR DELAY '00:00:10'
SELECT * FROM Team;
COMMIT TRANSACTION