use Swimming_competition;

-- Phantom read Transaction 2

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

-- Solution for the phantom read:
-- SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRANSACTION
SELECT * FROM Team WHERE tid % 2 = 0
WAITFOR DELAY '00:00:10'
SELECT * FROM Team WHERE tid % 2 = 0
COMMIT TRANSACTION